apiVersion: v1
kind: Service
metadata:
  name: kubedebugsess-proxy-svc
  namespace: kubedebugsess-system
spec:
  type: ClusterIP
  selector:
    app: kubedebugsess-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
