apiVersion: ajou.oxan0n.me/v1alpha1
kind: DebugSession
metadata:
  labels:
    app.kubernetes.io/name: kubedebugsess
    app.kubernetes.io/managed-by: kustomize
  name: debugsession-asdf
  namespace: test-app
spec:
  targetPodName: test-app-busybox-deploy-9c89c9ff7-cvh6r
  targetNamespace: test-app
  debuggerImage: registry.gitlab.com/oxan0n/toki-dev/busybox:1.0
  targetContainerName: test-app-busybox
