apiVersion: ajou.oxan0n.me/v1alpha1
kind: DebugSession
metadata:
  labels:
    app.kubernetes.io/name: kubedebugsess
    app.kubernetes.io/managed-by: kustomize
  name: debugsession-asdf
  namespace: test-app
spec:
  targetPodName: test-app-busybox-deploy-9c89c9ff7-8nh95
  targetNamespace: test-app
  debuggerImage: busybox
