apiVersion: ajou.oxan0n.me/v1alpha1
kind: DebugSession
metadata:
  labels:
    app.kubernetes.io/name: kubedebugsess
    app.kubernetes.io/managed-by: kustomize
  name: debugsession-asdf
  namespace: test-app
spec:
  targetPodName: test-app-busybox-deploy-5c9458ffcd-dwj8g
  targetNamespace: test-app
  targetContainerName: test-app-busybox
  debuggerImage: registry.gitlab.com/oxan0n/toki-dev/debugger-slim:6.0
  ttl: 600
  debugSecurity:
    runAsUser: 0
    runAsNonRoot: false
    privileged: false
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: true
    capabilities:
      add:
        - ALL
